# GET hello
GET http://localhost:8888/hello

### POST catrpc plguin
POST http://localhost:8888/gw/catrpc/com.abysscat.catrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "7f90d3ebfd077ad3c1bb7b05930080a1",
  "args": [100]
}

### POST catrpc plguin mock
POST http://localhost:8888/gw/com.abysscat.catrpc.demo.api.UserService?mock=true
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "7f90d3ebfd077ad3c1bb7b05930080a1",
  "args": [100]
}

### POST direct plugin
POST http://localhost:8888/gw/direct/com.abysscat.catrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "7f90d3ebfd077ad3c1bb7b05930080a1",
  "args": [100]
}

### POST direct plugin backend
POST http://localhost:8888/gw/direct/com.abysscat.catrpc.demo.api.UserService?backend=http://localhost:8082/catrpc
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "7f90d3ebfd077ad3c1bb7b05930080a1",
  "args": [100]
}